/** Canonical domain event type names published on the {@link EventBus}. */
export const DOMAIN_EVENTS = {
  CustomerCreated: 'customer.created',
  LicenceIssued: 'licence.issued',
  LicenceRenewed: 'licence.renewed',
  LicenceReissued: 'licence.reissued',
  LicenceSuspended: 'licence.suspended',
  LicenceReactivated: 'licence.reactivated',
  LicenceRevoked: 'licence.revoked',
  NotificationSent: 'notification.sent',
  NotificationFailed: 'notification.failed',
  PaymentRecorded: 'payment.recorded',
  DashboardCacheInvalidated: 'dashboard.cache_invalidated',
  SubscriptionCreated: 'subscription.created',
  SubscriptionActivated: 'subscription.activated',
  SubscriptionRenewed: 'subscription.renewed',
  SubscriptionCancelled: 'subscription.cancelled',
  SubscriptionExpired: 'subscription.expired',
  SubscriptionSuspended: 'subscription.suspended',
  PlanChanged: 'subscription.plan_changed',
  DeviceLimitChanged: 'subscription.device_limit_changed',
  InvoiceCreated: 'invoice.created',
  InvoicePaid: 'invoice.paid',
  InvoiceOverdue: 'invoice.overdue',
  PaymentSucceeded: 'billing.payment_succeeded',
  PaymentFailed: 'billing.payment_failed',
  ManualPaymentRecorded: 'billing.manual_payment_recorded',
} as const;

export type DomainEventType = (typeof DOMAIN_EVENTS)[keyof typeof DOMAIN_EVENTS];

/** Event types that should invalidate the dashboard summary cache when published. */
export const DASHBOARD_INVALIDATING_EVENTS: string[] = [
  DOMAIN_EVENTS.CustomerCreated,
  DOMAIN_EVENTS.LicenceIssued,
  DOMAIN_EVENTS.LicenceRenewed,
  DOMAIN_EVENTS.LicenceReissued,
  DOMAIN_EVENTS.LicenceSuspended,
  DOMAIN_EVENTS.LicenceReactivated,
  DOMAIN_EVENTS.LicenceRevoked,
  DOMAIN_EVENTS.NotificationSent,
  DOMAIN_EVENTS.NotificationFailed,
  DOMAIN_EVENTS.PaymentRecorded,
  DOMAIN_EVENTS.SubscriptionCreated,
  DOMAIN_EVENTS.SubscriptionActivated,
  DOMAIN_EVENTS.SubscriptionRenewed,
  DOMAIN_EVENTS.SubscriptionCancelled,
  DOMAIN_EVENTS.SubscriptionExpired,
  DOMAIN_EVENTS.SubscriptionSuspended,
  DOMAIN_EVENTS.PlanChanged,
  DOMAIN_EVENTS.InvoiceCreated,
  DOMAIN_EVENTS.InvoicePaid,
  DOMAIN_EVENTS.InvoiceOverdue,
  DOMAIN_EVENTS.PaymentSucceeded,
  DOMAIN_EVENTS.ManualPaymentRecorded,
];
